#!/usr/bin/env python3
"""
Generate C PROGMEM font headers from TTF files for the v1simple display.

Usage:
    pip install fonttools brotli
    python tools/create_font_headers.py

Outputs: include/JetBrainsMono.h, include/Roboto.h, include/Atkinson.h

The subset covers all characters rendered by the display firmware.
Re-run this script if you change DISPLAY_CHARS or update the source TTFs.
"""

import os
import sys
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INCLUDE_DIR = REPO_ROOT / "include"

# Characters actually rendered by the display (bands, digits, compass, labels)
DISPLAY_CHARS = "0123456789KaUuXLNESWMPABCDRkghz .:-/%+"

FONTS = [
    {
        "name": "JetBrainsMono",
        "array": "JetBrainsMonoFont",
        "ttf": "tools/fonts/JetBrainsMono-Regular.ttf",
        "out": "JetBrainsMono.h",
    },
    {
        "name": "Roboto",
        "array": "RobotoFont",
        "ttf": "tools/fonts/Roboto-Regular.ttf",
        "out": "Roboto.h",
    },
    {
        "name": "Atkinson",
        "array": "AtkinsonFont",
        "ttf": "tools/fonts/AtkinsonHyperlegible-Regular.ttf",
        "out": "Atkinson.h",
    },
]


def subset_ttf(src: Path, out: Path, chars: str) -> None:
    result = subprocess.run(
        [str(Path(sys.executable).parent / "fonttools"), "subset", str(src),
         f"--text={chars}", f"--output-file={out}"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"fonttools subset failed for {src.name}:\n{result.stderr}")


def ttf_to_header(ttf_path: Path, array_name: str, human_name: str) -> str:
    data = ttf_path.read_bytes()
    lines = [
        "// Auto-generated by tools/create_font_headers.py — do not edit manually.",
        f"// Source: {human_name} Regular, subsetted to display chars.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        f"static const uint8_t {array_name}[] PROGMEM = {{",
    ]
    row: list[str] = []
    for b in data:
        row.append(f"0x{b:02X}")
        if len(row) == 16:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row))
    lines += ["};", "", f"static const size_t {array_name}Size = sizeof({array_name});"]
    return "\n".join(lines) + "\n"


def main() -> None:
    tmp_dir = Path("/tmp/font_subset_work")
    tmp_dir.mkdir(exist_ok=True)

    for font in FONTS:
        src = REPO_ROOT / font["ttf"]
        if not src.exists():
            print(f"SKIP {font['name']}: {src} not found — place TTF in tools/fonts/")
            continue

        subset_path = tmp_dir / f"{font['name']}-subset.ttf"
        print(f"Subsetting {font['name']}...", end=" ", flush=True)
        subset_ttf(src, subset_path, DISPLAY_CHARS)

        header = ttf_to_header(subset_path, font["array"], font["name"])
        out_path = INCLUDE_DIR / font["out"]
        out_path.write_text(header)

        src_kb = src.stat().st_size / 1024
        out_kb = subset_path.stat().st_size / 1024
        print(f"{src_kb:.0f} KB → {out_kb:.0f} KB subset → {out_path.name}")

    print("Done.")


if __name__ == "__main__":
    main()
